 /*	
**********************************************************************
COMPARA VENDAS (TICKETS) LOJAS VS RETAGUARDA

COMPARAÇÕES NA TABELA LOJA_VENDA
	QTDE_TOTAL, VALOR_PAGO OU SE O TICKET NÃO EXISTIR NA RETAGUAR

AO ENCONTRAR ALGUMA DAS CONDIÇÕES ACIMA É EXECUTADO:
	NA LOJA:
	SE LOJA_VENDA ESTIVER COM O CAMPO TICKET_IMPRESSO = 1
	E  LOJA_VENDA_PGTO ESTIVER COM O CAMPO VENDA_FINALIZADA = 1
	
	UPDATE PARA FORÇAR DATA_PARA_TRANSFERENCIA NAS TABELAS:
		LOJA_VENDA
		LOJA_VENDA_PGTO

CRIADO POR: DANILO RUSSO
CRIADO EM: 11/07/2018
***********************************************************************
*/
SET NOCOUNT OFF

use Cliente398_ERP

-- DECLARANDO VARIÁVEIS

DECLARE @CODIGO CHAR(6),
		@LOJA CHAR(25), 
		@SERVER NVARCHAR(70),
		@RETVAL INT, 
		@COMANDO NVARCHAR(MAX), 
		@SERVERFULL NVARCHAR(MAX),
		@SERVERFULL2 NVARCHAR(MAX),
		@SERVERFULL3 NVARCHAR(MAX),
		@SERVERFULL4 NVARCHAR(MAX),
		@BANCO VARCHAR(20),
		@DATA DATE,
		@DATA_FIM DATE,
		@QTDEST NUMERIC(5), 
		@TOTALST NUMERIC(10,2),
		@QTDEHQ NUMERIC(5), 
		@TOTALHQ NUMERIC(10,2),
		@BODY NVARCHAR(MAX),
		@HTML NVARCHAR(MAX),
		@TICKET VARCHAR(10),
		@TERMINAL VARCHAR(3)
--########################################################################################################
SET @DATA = '20190120'--CONVERT(DATE,GETDATE()-2)
SET @DATA_FIM = '20190131'--CONVERT(DATE,GETDATE()-1)
--#########################################################################################################

 --SELECT @DATA AS DATA_VENDA

-- CRIANDO TABELA DE DADOS

IF OBJECT_ID('TEMPDB..#EL_COMPARA_VENDA_ST_HQ') IS NOT NULL 
BEGIN
     DROP TABLE #EL_COMPARA_VENDA_ST_HQ
END

CREATE TABLE #EL_COMPARA_VENDA_ST_HQ(
	[DATA_PROC] [DATETIME] NULL,
	[DATA_INI] DATE NULL,
	[DATA_FIM] DATE NULL,
	[SERVER] VARCHAR(MAX) NULL,
	[BANCO] VARCHAR(MAX) NULL,
	[DT_VDA] [DATE] NULL,
	[CODIGO] [VARCHAR](06) NULL,
	[FILIAL] [VARCHAR](25) NULL,
	[TICKET] [VARCHAR](10) NULL,
	[LANCAMENTO_CAIXA] [VARCHAR](7) NULL,
	[TERMINAL] [VARCHAR](3) NULL,
	[TKT_IMPR] [VARCHAR](1) NULL,
	[TKT_FIN] [VARCHAR](1) NULL,
	[UNITS_ST] [NUMERIC](5, 0) NULL,
	[SALES_ST] [NUMERIC](10, 2) NULL,
	[UNITS_HQ] [NUMERIC](5, 0) NULL,
	[SALES_HQ] [NUMERIC](10, 2) NULL,
	[NF] [VARCHAR](15) NULL,
	[SERIE] [VARCHAR](6) NULL,
	[CF] [VARCHAR](9) NULL,
	[NF_CANC] [VARCHAR](15) NULL,
	[OBS] [VARCHAR](20) NULL
) ON [PRIMARY]

-- DADOS PARA O CURSOR

DECLARE STORE_CURSOR CURSOR FOR 

SELECT C.COD_FILIAL, RTRIM(A.FILIAL) AS LOJA, 
RTRIM(A.VALOR_PROPRIEDADE) AS 'SERVER', 
RTRIM(B.VALOR_PROPRIEDADE) AS 'BANCO'
FROM (SELECT B.FILIAL, B.PROPRIEDADE, B.VALOR_PROPRIEDADE FROM PROPRIEDADE A JOIN PROP_FILIAIS B ON A.PROPRIEDADE = B.PROPRIEDADE
	  WHERE TITULO_PROPRIEDADE ='LINKED_SERVER'  AND (VALOR_PROPRIEDADE IS NOT NULL AND (VALOR_PROPRIEDADE <> 'SERVER'AND VALOR_PROPRIEDADE <> '' ))) A 
JOIN (SELECT B.FILIAL, B.PROPRIEDADE, B.VALOR_PROPRIEDADE FROM PROPRIEDADE A JOIN PROP_FILIAIS B ON A.PROPRIEDADE = B.PROPRIEDADE
	  WHERE DESC_PROPRIEDADE ='BANCO DA LOJA' AND B.VALOR_PROPRIEDADE IS NOT NULL) B 
	ON A.FILIAL = B.FILIAL 
JOIN (SELECT COD_FILIAL, FILIAL, REDE_LOJAS FROM FILIAIS WHERE DATA_FECHAMENTO IS NULL) C ON A.FILIAL = C.FILIAL
WHERE C.COD_FILIAL  IN ( '0286','0280')--,'0287','0282','','','','','','','','0288','','')
ORDER BY 1

-- ABRINDO O CURSOR
OPEN STORE_CURSOR

FETCH NEXT FROM STORE_CURSOR 
INTO @CODIGO, @LOJA, @SERVER, @BANCO

WHILE @@FETCH_STATUS = 0
BEGIN

BEGIN TRY
    EXEC @RETVAL = sys.sp_testlinkedserver @SERVER
END TRY
BEGIN CATCH
    SET @RETVAL = SIGN(@@ERROR);
END CATCH;

IF @RETVAL <> 0
BEGIN
BEGIN TRY
    EXEC @RETVAL = sys.sp_testlinkedserver @SERVER
END TRY
BEGIN CATCH
    SET @RETVAL = SIGN(@@ERROR);
END CATCH;
END

IF @RETVAL =0
BEGIN
SET @SERVERFULL = '['+RTRIM(@SERVER)+']'+'.'+RTRIM(@BANCO)+'.dbo.LOJA_VENDA'
SET @SERVERFULL2 = '['+RTRIM(@SERVER)+']'+'.'+RTRIM(@BANCO)+'.dbo.LOJA_VENDA_PGTO'
	
SET @COMANDO='
SELECT GETDATE(), '''+CONVERT(VARCHAR(10),@DATA)+''','''+CONVERT(VARCHAR(10),@DATA_FIM)+''',
'''+RTRIM(@SERVER)+''','''+RTRIM(@BANCO)+''',
CONVERT(DATE,B.DATA_VENDA),A.COD_FILIAL, RTRIM(FILIAL) AS FILIAL, B.TICKET, B.LANCAMENTO_CAIXA,B.TERMINAL, B.QTDE_TOTAL, B.VALOR_PAGO, C.QTDE_TOTAL,  C.VALOR_PAGO, B.TICKET_IMPRESSO, D.VENDA_FINALIZADA, D.NUMERO_FISCAL_VENDA, D.SERIE_NF_SAIDA, D.NUMERO_CUPOM_FISCAL, D.NUMERO_FISCAL_CANCELAMENTO,
CASE 
	WHEN B.QTDE_TOTAL = C.QTDE_TOTAL AND C.VALOR_PAGO = B.VALOR_PAGO THEN ''OK''
	WHEN B.QTDE_TOTAL <> C.QTDE_TOTAL AND C.VALOR_PAGO = B.VALOR_PAGO THEN ''APURAR - QTDE DIF''
	WHEN B.QTDE_TOTAL = C.QTDE_TOTAL AND C.VALOR_PAGO <> B.VALOR_PAGO THEN ''APURAR - VALOR DIF''
	ELSE ''APURAR - TUDO DIF'' END
FROM (SELECT COD_FILIAL, FILIAL FROM FILIAIS WHERE FILIAL = '''+RTRIM(@LOJA)+''') A
LEFT JOIN (SELECT CODIGO_FILIAL, DATA_VENDA, TICKET, QTDE_TOTAL, VALOR_PAGO, TICKET_IMPRESSO, TERMINAL, LANCAMENTO_CAIXA FROM '+RTRIM(@SERVERFULL)+
	' WHERE CONVERT(DATE,DATA_VENDA) BETWEEN '''+CONVERT(CHAR(10),@DATA)+''' AND '''+CONVERT(CHAR(10),@DATA_FIM)+''' AND CODIGO_FILIAL = '''+RTRIM(@CODIGO)+''')B 
	ON B.CODIGO_FILIAL COLLATE SQL_LATIN1_GENERAL_CP1_CI_AS = A.COD_FILIAL COLLATE SQL_LATIN1_GENERAL_CP1_CI_AS 
LEFT JOIN (SELECT CODIGO_FILIAL, TICKET, DATA_VENDA, QTDE_TOTAL, VALOR_PAGO FROM LOJA_VENDA WHERE CONVERT(DATE,DATA_VENDA) BETWEEN '''+CONVERT(CHAR(10),@DATA)+''' AND '''+CONVERT(CHAR(10),@DATA_FIM)+''' AND CODIGO_FILIAL = '''+RTRIM(@CODIGO)+''') C 
	ON B.CODIGO_FILIAL COLLATE SQL_LATIN1_GENERAL_CP1_CI_AS = C.CODIGO_FILIAL COLLATE SQL_LATIN1_GENERAL_CP1_CI_AS 
		AND B.DATA_VENDA = C.DATA_VENDA 
		AND B.TICKET COLLATE SQL_LATIN1_GENERAL_CP1_CI_AS = C.TICKET COLLATE SQL_LATIN1_GENERAL_CP1_CI_AS 
JOIN (SELECT CODIGO_FILIAL, DATA, TERMINAL, LANCAMENTO_CAIXA, VENDA_FINALIZADA, NUMERO_FISCAL_VENDA,SERIE_NF_SAIDA, NUMERO_CUPOM_FISCAL,NUMERO_FISCAL_CANCELAMENTO FROM ' +RTRIM(@SERVERFULL2)+' WHERE CONVERT(DATE,DATA) BETWEEN '''+CONVERT(CHAR(10),@DATA)+''' AND '''+CONVERT(CHAR(10),@DATA_FIM)+''' AND  CODIGO_FILIAL = '''+RTRIM(@CODIGO)+''') D 
	ON B.CODIGO_FILIAL COLLATE SQL_LATIN1_GENERAL_CP1_CI_AS = D.CODIGO_FILIAL COLLATE SQL_LATIN1_GENERAL_CP1_CI_AS 
		AND B.DATA_VENDA = D.DATA
		AND B.TERMINAL COLLATE SQL_LATIN1_GENERAL_CP1_CI_AS = D.TERMINAL COLLATE SQL_LATIN1_GENERAL_CP1_CI_AS 
		AND B.LANCAMENTO_CAIXA COLLATE SQL_LATIN1_GENERAL_CP1_CI_AS = D.LANCAMENTO_CAIXA COLLATE SQL_LATIN1_GENERAL_CP1_CI_AS
WHERE ISNULL(B.QTDE_TOTAL,0) <> ISNULL(C.QTDE_TOTAL,0) OR ISNULL(C.VALOR_PAGO,0) <> ISNULL(B.VALOR_PAGO,0)'


PRINT @COMANDO		
INSERT INTO #EL_COMPARA_VENDA_ST_HQ(DATA_PROC, DATA_INI, DATA_FIM, SERVER, BANCO,DT_VDA,CODIGO, FILIAL, TICKET, LANCAMENTO_CAIXA,TERMINAL, UNITS_ST, SALES_ST, UNITS_HQ, SALES_HQ, TKT_IMPR, TKT_FIN, NF, SERIE,CF,NF_CANC,OBS)
EXEC (@COMANDO)
END


IF @RETVAL <> 0
BEGIN
  
INSERT INTO #EL_COMPARA_VENDA_ST_HQ(DATA_PROC, DATA_INI, DATA_FIM,SERVER, BANCO, DT_VDA,CODIGO, FILIAL, UNITS_ST, SALES_ST, UNITS_HQ, SALES_HQ, OBS)
SELECT  GETDATE(), @DATA, @DATA_FIM, @SERVER, @BANCO, @DATA,RTRIM(@CODIGO), RTRIM(@LOJA),0,0, 
	CASE WHEN SUM(ISNULL(A.QTDE_TOTAL,0)-ISNULL(A.QTDE_TROCA_TOTAL,0)) = 0 OR SUM(ISNULL(A.QTDE_TOTAL,0)-ISNULL(A.QTDE_TROCA_TOTAL,0)) IS NULL
	THEN 0 ELSE SUM(ISNULL(A.QTDE_TOTAL,0)-ISNULL(A.QTDE_TROCA_TOTAL,0)) END,
	CASE WHEN SUM(ISNULL(A.VALOR_PAGO,0)) = 0 OR SUM(ISNULL(A.VALOR_PAGO,0)) IS NULL THEN 0 ELSE SUM(ISNULL(A.VALOR_PAGO,0)) END, 'OFFLINE'
FROM LOJA_VENDA A
JOIN FILIAIS B ON A.CODIGO_FILIAL = B.COD_FILIAL
WHERE RTRIM(B.FILIAL) = RTRIM(@LOJA) AND CONVERT(DATE,DATA_VENDA)= @DATA

END

FETCH NEXT FROM STORE_CURSOR 
INTO @CODIGO, @LOJA, @SERVER, @BANCO
END 

CLOSE STORE_CURSOR;
DEALLOCATE STORE_CURSOR;

IF OBJECT_ID('TEMPDB..#DISPLAY') IS NOT NULL 
BEGIN
     DROP TABLE #DISPLAY
END


SELECT NRO = IDENTITY(INT , 1, 1),
DATA_PROC, DATA_INI, DATA_FIM, SERVER, BANCO,
DT_VDA,
CODIGO,
SUBSTRING(FILIAL,1,25) AS STORE, 
TICKET,
LANCAMENTO_CAIXA,
TERMINAL,
CONVERT(CHAR(5),UNITS_ST) AS UNITS_ST, 
CONVERT(CHAR(9),SALES_ST) AS SALES_ST ,  
CONVERT(CHAR(5),UNITS_HQ) AS UNITS_HQ, 
CONVERT(CHAR(9),SALES_HQ) AS SALES_HQ ,
TKT_IMPR AS VDA_IMP,
TKT_FIN AS PGTO_FIN,
NF, SERIE,
CF, NF_CANC,
OBS
INTO #DISPLAY
FROM #EL_COMPARA_VENDA_ST_HQ
WHERE NF IS  NOT NULL OR  CF IS NOT NULL 
ORDER BY OBS

SELECT * FROM #EL_COMPARA_VENDA_ST_HQ

TRUNCATE TABLE ELC_VERIFICA_TICKETS_LOJAS_ERP
INSERT INTO ELC_VERIFICA_TICKETS_LOJAS_ERP
SELECT *, '01' AS ULTIMO_STATUS , GETDATE() DT_ULTIMO_STATUS 
FROM #EL_COMPARA_VENDA_ST_HQ
WHERE NF IS  NOT NULL OR  CF IS NOT NULL 



SELECT * FROM #DISPLAY ORDER BY OBS, CODIGO,STORE, DT_VDA 
SELECT * FROM #DISPLAY 
WHERE NF IS NOT NULL OR SERIE IS NOT NULL OR CF IS NOT NULL OR NF_CANC IS NOT NULL
 ORDER BY OBS, CODIGO,STORE, DT_VDA

-- DADOS PARA O CURSOR 2


DECLARE STORE_CURSOR CURSOR FOR 
SELECT CODIGO, STORE, SERVER, BANCO, DT_VDA, TICKET, TERMINAL FROM #DISPLAY WHERE OBS LIKE 'APURAR%' ORDER BY OBS, CODIGO,STORE, DT_VDA

-- ABRINDO O CURSOR
OPEN STORE_CURSOR

FETCH NEXT FROM STORE_CURSOR 
INTO  @CODIGO, @LOJA, @SERVER, @BANCO, @DATA,  @TICKET, @TERMINAL

WHILE @@FETCH_STATUS = 0
BEGIN

BEGIN TRY
    EXEC @RETVAL = sys.sp_testlinkedserver @SERVER
END TRY
BEGIN CATCH
    SET @RETVAL = SIGN(@@ERROR);
END CATCH;


IF @RETVAL <> 0
BEGIN
BEGIN TRY
    EXEC @RETVAL = sys.sp_testlinkedserver @SERVER
END TRY
BEGIN CATCH
    SET @RETVAL = SIGN(@@ERROR);
END CATCH;
END


IF @RETVAL =0
	BEGIN
	SET @SERVERFULL = '['+RTRIM(@SERVER)+']'+'.'+RTRIM(@BANCO)+'.dbo.LOJA_VENDA'
	SET @SERVERFULL2 = '['+RTRIM(@SERVER)+']'+'.'+RTRIM(@BANCO)+'.dbo.LOJA_VENDA_PGTO'
	SET @SERVERFULL3 = '['+RTRIM(@SERVER)+']'+'.'+RTRIM(@BANCO)+'.dbo.LOJA_NOTA_FISCAL'
	SET @SERVERFULL4 = '['+RTRIM(@SERVER)+']'+'.'+RTRIM(@BANCO)+'.dbo.CLIENTES_VAREJO'


-- UPDATE LOJA_VENDA
select getdate()		
SET @COMANDO='
UPDATE A SET A.TICKET = A.TICKET--, TICKET_IMPRESSO = ''1''
FROM ' +RTRIM(@SERVERFULL)+' A  
WHERE CODIGO_FILIAL = '''+RTRIM(@CODIGO)+''' 
		AND DATA_VENDA = '''+CONVERT(CHAR(10),@DATA)+'''
		AND TICKET = '''+RTRIM(@TICKET)+'''
		AND TERMINAL = '''+RTRIM(@TERMINAL)+''''
PRINT @COMANDO		
EXEC (@COMANDO)

-- UPDATE LOJA_VENDA_PGTO
select getdate()
SET @COMANDO='
UPDATE B SET B.LANCAMENTO_CAIXA = B.LANCAMENTO_CAIXA, VENDA_FINALIZADA = ''1''
FROM ' +RTRIM(@SERVERFULL)+' A  
JOIN ' +RTRIM(@SERVERFULL2)+' B ON A.CODIGO_FILIAL = B.CODIGO_FILIAL AND A.TERMINAL = B.TERMINAL AND A.LANCAMENTO_CAIXA = B.LANCAMENTO_CAIXA AND A.DATA_VENDA = B.DATA
WHERE A.CODIGO_FILIAL = '''+RTRIM(@CODIGO)+''' 
		AND DATA_VENDA = '''+CONVERT(CHAR(10),@DATA)+'''
		AND TICKET = '''+RTRIM(@TICKET)+'''
		AND A.TERMINAL = '''+RTRIM(@TERMINAL)+''''
PRINT @COMANDO		
EXEC (@COMANDO)


-- UPDATE LOJA_NOTA_FISCAL
select getdate()
SET @COMANDO='
UPDATE C SET C.NF_NUMERO = C.NF_NUMERO
FROM ' +RTRIM(@SERVERFULL)+' A  
JOIN ' +RTRIM(@SERVERFULL2)+' B ON A.CODIGO_FILIAL = B.CODIGO_FILIAL AND A.TERMINAL = B.TERMINAL AND A.LANCAMENTO_CAIXA = B.LANCAMENTO_CAIXA AND A.DATA_VENDA = B.DATA
JOIN ' +RTRIM(@SERVERFULL3)+' C ON A.CODIGO_FILIAL = B.CODIGO_FILIAL 
							AND B.NUMERO_FISCAL_VENDA = C.NF_NUMERO 
							AND B.SERIE_NF_SAIDA = C.SERIE_NF
WHERE A.CODIGO_FILIAL = '''+RTRIM(@CODIGO)+''' 
		AND DATA_VENDA = '''+CONVERT(CHAR(10),@DATA)+'''
		AND TICKET = '''+RTRIM(@TICKET)+'''
		AND A.TERMINAL = '''+RTRIM(@TERMINAL)+''''
PRINT @COMANDO		
EXEC (@COMANDO)

/*
SET @COMANDO='
UPDATE B SET B.CODIGO_CLIENTE = B.CODIGO_CLIENTE
FROM (SELECT CODIGO_FILIAL,DATA_VENDA, TICKET, TERMINAL, CODIGO_CLIENTE FROM ' +RTRIM(@SERVERFULL)+'  
WHERE CODIGO_FILIAL = '''+RTRIM(@CODIGO)+''' 
		AND DATA_VENDA = '''+CONVERT(CHAR(10),@DATA)+'''
		AND TICKET = '''+RTRIM(@TICKET)+'''
		AND TERMINAL = '''+RTRIM(@TERMINAL)+''') A  
JOIN (SELECT CODIGO_CLIENTE FROM '+RTRIM(@SERVERFULL4)+' WHERE CODIGO_CLIENTE IN  
	 (SELECT CODIGO_CLIENTE FROM ' +RTRIM(@SERVERFULL)+'
	 WHERE CODIGO_FILIAL = '''+RTRIM(@CODIGO)+''' 
		AND DATA_VENDA = '''+CONVERT(CHAR(10),@DATA)+'''
		AND TICKET = '''+RTRIM(@TICKET)+'''
		AND TERMINAL = '''+RTRIM(@TERMINAL)+''')) B ON A.CODIGO_CLIENTE = B.CODIGO_CLIENTE'
PRINT @COMANDO		
-----EXEC (@COMANDO)
*/
END


--PRINT @RETVAL
IF @RETVAL <> 0
BEGIN
	SET @RETVAL = @RETVAL
END

FETCH NEXT FROM STORE_CURSOR 
INTO  @CODIGO, @LOJA, @SERVER, @BANCO, @DATA,  @TICKET, @TERMINAL

END 

CLOSE STORE_CURSOR;
DEALLOCATE STORE_CURSOR;

INSERT INTO ELC_VERIFICA_TICKETS_LOJAS_ERP
SELECT *, '01' AS ULTIMO_STATUS , GETDATE() DT_ULTIMO_STATUS 
FROM #EL_COMPARA_VENDA_ST_HQ
where 
OBS <> 'OK'
OR (TKT_IMPR=0 AND TKT_IMPR = 0 AND NF IS NULL AND SERIE IS NULL AND SERIE IS NULL AND SERIE IS NULL AND CF IS NULL AND NF_CANC IS NULL)

-- TRUNCATE TABLE ELC_VERIFICA_TICKETS_LOJAS_ERP
select * from ELC_VERIFICA_TICKETS_LOJAS_ERP order by DATA_PROC desc


--INSERT INTO ELC_VERIFICA_TICKETS_LOJAS_ERP
--SELECT * FROM #EL_COMPARA_VENDA_ST_HQ


SELECT DISTINCT RTRIM(STORE) FROM #DISPLAY 
select * from #EL_COMPARA_VENDA_ST_HQ